import Head from "next/head";
import {
  Stack,
  Card,
  CardContent,
  CardActions,
  Typography,
  Container,
  Link,
  Chip,
  Box,
  List,
  Button,
  ListItem,
  AppBar,
  Toolbar,
  Divider,
  ListItemText,
  ListItemIcon,
} from "@mui/material";

import BoltIcon from "@mui/icons-material/Bolt";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import { getLastFivePosts } from "../services/post.service";

export async function getStaticProps() {
  const posts = JSON.stringify(await getLastFivePosts());

  return {
    props: {
      posts,
    },
  };
}

export default function Home(props) {
  const posts = JSON.parse(props.posts);
  return (
    <>
      <Head>
        <title>Blog Summary</title>
        <meta name="blog summaries" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <AppBar component="nav">
          <Toolbar>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              Post Summaries
            </Typography>
          </Toolbar>
        </AppBar>
        <Container
          maxWidth="md"
          sx={{ paddingTop: "86px", paddingBottom: "24px" }}
        >
          <Stack spacing={2}>
            {posts.map((post) => (
              <Card key={post.id}>
                <CardContent>
                  <Stack direction="row" justifyContent="space-between">
                    <Typography color="text.secondary" gutterBottom>
                      {post.blog}
                    </Typography>
                    <Stack direction="row" spacing={1}>
                      {post.tags.map((tag, idx) => (
                        <Chip
                          label={tag}
                          key={idx}
                          variant="outlined"
                          size="small"
                        />
                      ))}
                    </Stack>
                  </Stack>
                  <Typography variant="h5" component="div">
                    {post.title}
                  </Typography>
                  <List>
                    {post.summary.map((item, idx) => (
                      <ListItem key={idx}>
                        <ListItemIcon>
                          <BoltIcon />
                        </ListItemIcon>
                        <ListItemText>{item}</ListItemText>
                      </ListItem>
                    ))}
                  </List>
                </CardContent>
                <Divider light />
                <CardActions>
                  <Button
                    fullWidth
                    component={Link}
                    to={post.href}
                    target="_blank"
                    color="primary"
                  >
                    Read Full Article{" "}
                    <ArrowForwardIcon sx={{ fontSize: "16px" }} />
                  </Button>
                </CardActions>
              </Card>
            ))}
          </Stack>
        </Container>
      </Box>
    </>
  );
}
