import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getLastFivePosts } from "../services/post.service"
import BluredBackground from "../components/BluredBackground";
import Header from "../components/Header";

export async function getStaticProps() {
  const date = new Date().toISOString().split('T')[0];
  const posts = JSON.stringify(await getLastFivePosts());

  return {
    props: {
      date,
      posts,
    },
  }
}

export default function Home(props) {
  const posts = JSON.parse(props.posts);
  const date = new Date(props.date).toDateString();
  return (
    <div>
      <Head>
        <title>Blog Summary</title>
        <meta name="blog summaries" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BluredBackground />
      <Header date={date} />

      <main >

        <div className={styles.grid}>
          {posts.map(post =>
              <a href={post.href} key={post.id} target="_blank" className={styles.card}>
                <p>{post.blog}</p>
                <h2>{post.title}</h2>
                <ul>
                  {post.summary.map(item =>
                  <li key={item}>{item}</li>
                  )}
                </ul>
              </a>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
